name: Node CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: ESLint
        run: npm run lint
  release:
    needs: [lint]
    name: Build and release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build TypeScript
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "kaaaxcreatorsBOT"
          GIT_AUTHOR_EMAIL: "bernd@kaaaxcreators.de"
          GIT_COMMITTER_NAME: "kaaaxcreatorsBOT"
          GIT_COMMITTER_EMAIL: "bernd@kaaaxcreators.de"